### ISSUE TITLE
3.1 KPI metrics for dashboard 

### ISSUE THREAD

**Issue by flo351** [Irisvella/InventoryPilot#58]
**Acceptance Criteria:**
KPI Dashboard Page:
**Displays critical KPIs:**
1. Cycle Time Per Order
2. Order Picking Accuracy
3. Warehouse Throughput 
4. Stock Levels (by SKU)
5. Order Fulfillment Rate

**Navigation:**
A working "KPI" button in the Sidebar takes users to the KPI Dashboard page.
Sidebar link uses React Router for seamless navigation.
**Visual Design:**
KPIs are displayed as cards or tables in a grid layout.
Responsive design ensures the dashboard is viewable on different screen sizes.
Parent User Story: #10

**Comment by sarahabellard** [comment]
For the stocklevel KPI, since there are thousands of different parts to track, it will be more efficient to visualise it in a table rather than a graph, in the KPI dashboard we should implement something like this
![Screenshot 2024-12-26 at 4 00 37 PM](https://github.com/user-attachments/assets/541f9b16-c438-4e72-a2de-180040a97e11)

**Comment by sarahabellard** [comment]
Future enhancement, we could add a status colomn on table for dashboard. With a threshold for when stock levels are low

**Comment by sarahabellard** [comment]
Will keep static pages for now and push to main, the full feature plan and design will be added to the issue that contains the sub issues #10

**Comment by sarahabellard** [comment]
![image](https://github.com/user-attachments/assets/165a03ab-772f-4d11-8817-18121d336375)
current static KPI dashboard completed in #10

full functionalities and new designed moved to #10
